In [2]:
import numpy as np
tableau1=np.array([ 1,5,7,8])
tableau1

array([1, 5, 7, 8])

In [4]:
#tableau2=np.array([1,2,3,4,5,6,7,8,9])
#tableau2
tableau2=np.arange(1,10)
tableau2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
## 3. Créer un tableau de 10 éléments rempli de 0
table=np.zeros(10, dtype="int")
table
#table=np.full(10,0)
#table

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
#4. Créer un tableau de 2 lignes 5 colonnes rempli de 0
#table1=np.full((2,5),0)
table1=np.zeros((2,5))
table1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
#5. Créer un tableau de 10 éléments rempli de 1
table2=np.ones(10)
table2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
#6. Créer un tableau de 2 lignes 5 colonnes rempli de 1
table3=np.ones((2,5))
table3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
#7. Créer un tableau de 10 éléments rempli 8.5
table4=np.full((1,10),8.5)
table4

array([[8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5]])

In [38]:
#8. Créer un tableau de série d'entiers successifs allant de 1 à 9 inclus
tableS=np.array(range(1,10))
tableS

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#9. Créer un tableau de 3 lignes et 3 colonnes rempli de série d'entiers successifs allant de 1 à 9 inclus
#tables1=np.array([[1,2,3],[4,5,6],[7,8,9]])
tables1=np.arange(1,10).reshape(3,3)
tables1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#10.Créer une matrice identité de 4 lignes 4 colonnes
matricei =np.identity(4)
matricei

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#11. Tableau rempli de valeurs aléatoires normales centrées en zéro
tableB=np.linspace(-5,5,5)
tableB

array([-5. , -2.5,  0. ,  2.5,  5. ])

In [33]:
#12.Créer un tableau rempli de 20 valeurs aléatoires entières comprises entre 1 et
10
tableauA=np.random.randint(2,10,size=20)
tableauA

array([7, 5, 3, 9, 7, 6, 4, 9, 5, 2, 6, 9, 3, 6, 7, 2, 8, 4, 6, 4])

In [34]:
#13.Transformer le tableau précédent en matrice de 4 lignes et 5 colonnes
matrice=tableauA.reshape((4,5))
matrice

array([[7, 5, 3, 9, 7],
       [6, 4, 9, 5, 2],
       [6, 9, 3, 6, 7],
       [2, 8, 4, 6, 4]])

In [22]:
#14.Créer un tableau de 5 éléments compris entre 0 et 1 avec une amplitude égale
tab=np.linspace(0,1,5)
tab

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [82]:
type =tab.dtype
type

dtype('float64')

EXERCICE2

In [71]:
#1. Afficher le nombre de lignes et de colonnes
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [70]:
#2. Afficher la dimension de mon tableau
a.ndim

2

In [69]:
#3. Afficher le nombre d'élément de mon tableau
a.size

9

In [72]:
#4. Afficher le type des éléments du tableau
a.dtype

dtype('int32')

EXERCICE3

In [94]:
#1. afficher la valeur 5 qui est dans le tableau
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[1,1])

5


In [95]:
#2. Remplacer le 5 qui est dans le tableau par 0
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[b ==5 ] = 0
b

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [96]:
#3. afficher les chiffres 3, 6 et 9 du tableau
print(b[0,2])
print(b[1,2])
print(b[2,2])

3
6
9


In [104]:
#4. créer un tableau de 4 lignes et 3 colonnes rempli de 12 nombres entiersaléatoires compris entre 0 et 9
import random
F= np.random.randint(9,size = (4,3))
F


array([[6, 6, 8],
       [4, 8, 1],
       [6, 8, 7],
       [2, 0, 2]])

In [109]:
type=F.dtype
type

dtype('int32')

In [110]:
#5. Vérifier qu’il y a des nombres inférieur à 5
print(F<5)


[[False False False]
 [ True False  True]
 [False False False]
 [ True  True  True]]


In [111]:
#6. Remplacer les nombres inférieurs à 5 par 0
F[F<5]=0
F

array([[6, 6, 8],
       [0, 8, 0],
       [6, 8, 7],
       [0, 0, 0]])

EXERCICE4

In [133]:
#1. Créer un tableau de 4 lignes et 3 colonnes rempli de 11 nombres entiersaléatoires compris entre 0 et 9
T=np.random.randint(9,size=(4,3))
T



array([[4, 1, 8],
       [6, 2, 6],
       [7, 5, 1],
       [8, 1, 5]])

In [134]:
#2. Quel est le type des éléments du tableau ?
type=T.dtype
type

dtype('int32')

In [135]:
#3. Changer de type des éléments du tableau en float32
T=np.floor(10*np.random.random((3,4)))
T

array([[6., 8., 0., 5.],
       [3., 1., 0., 9.],
       [9., 6., 2., 5.]])

In [136]:
T.ndim

2

In [137]:
type=T.dtype
type

dtype('float64')

In [139]:
#4. Ajouter le chiffre 3 à la fin du tableau à une dimension
T=np.floor(10*np.random.random((3,4)))
d1 = reduce(lambda a,b:a+b,T)
d1


NameError: name 'reduce' is not defined